### ISSUE TITLE
Weird visual(?) glitch/bug with AI's output.

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#168] opened 2022-09-26 01:10 UTC
In short, no matter the output (as in context), the outputted line would always miss the first word/token(?).

As a rough example, the AI should output something like "This is the forest.", but instead writes " is the forest.".

**Comment by one-some** [comment] 2022-09-26 03:14
Fixed a bug in the prompt shaver thing in #169 that might be the cause of this

**Comment by ebolam** [comment] 2022-10-13 16:54
Closing as assumed PR 169 fixed it.

**Closed as completed by ebolam** 2022-10-13 16:54 UTC
Labels: Waiting to reproduce
