### ISSUE TITLE
Clicking undo a couple of times in succession retains text

### ISSUE THREAD

**Issue by ghost** [ebolam/KoboldAI#274] opened 2022-10-31 04:50 UTC
Clicking undo a couple of times in succession retains text, don't know if it's just a visual bug but clicking save and  loading also shows the same text that is not removed. It also seems like I cannot delete text after this.

**Comment by ebolam** [comment] 2022-10-31 19:46
Was there any errors? If you can reproduce, it would be helpful to get a debug log (click the download debug log link in the settings flyout [left one] in the home tab)

**Comment by ghost** [comment] 2022-11-01 11:28
I can give you my save file if you like. Though in pm only

**Comment by ebolam** [comment] 2022-11-01 11:33
Might be helpful. I haven't had a chance to attempt to recreate yet though.

**Comment by ghost** [comment] 2022-11-01 11:51
Is uploading here private or can I dm you in discord?

**Comment by ghost** [comment] 2022-11-01 12:29
I think it's reproduceable by clicking redo multiple times in succession

**Comment by ebolam** [comment] 2022-11-01 12:37
Here is public

**Comment by MrXen0morph** [comment] 2022-11-02 05:07
Can confirm that this strange behaviour is a thing. Like the OP mention, clicking ~~retry~~ undo multiple times. Here's the important detail, do it fast, without waiting for the last prompt to be removed.

**Comment by ghost** [comment] 2022-11-02 07:22
I think I made a mistake with what I meant though. What I meant with redo is back button or it should be undo.

**Comment by RaphaelNunes10** [comment] 2022-11-02 20:02
Yeah... I'm having this problem as well. It gets worse the more you try to mess with it, sometimes even erasing some generations or scrambling them, making the story all wacky.

It also corrupts the save permanently (or at least it doesn't get fixed even after restarting the service).

**Comment by ebolam** [comment] 2022-11-03 19:31
@RaphaelNunes10 what exactly are you doing to get the bug? I'm still having some difficulty getting this to replicate. Are you simply hitting undo until it gets messed up? Is it undos with submits? With or without text?

**Comment by ghost** [comment] 2022-11-03 19:48
@ebolam That's what I'm getting, the same with @RaphaelNunes10, basically just undoing a couple of times then it retains text. It happens with the save file I gave you.

**Comment by RaphaelNunes10** [comment] 2022-11-03 21:19
@ebolam The thing is, I'm not sure myself. I didn't even know what was causing it before I came here to report the issue and saw that @candymint23 already reported something similar.

I was generating without text for most of the time.

It's weird that you can't reproduce it, because it has happened so frequently to me that so far I've not being able to enjoy KoboldAI with the new UI to the fullest, fearing that my long-running stories get corrupted. 

Things I did other than hit undo was add entries to the World Info, Memory, Author Notes and Phrase/Word Bias, haven't changed anything else.

I should also mention that I've used the keyboard shortcut Ctrl-Z to undo and hit the Generate button while its generating to stop it mid-thorught a couple of times.

After a while, something happens to the saved story where it doesn't allow to delete some of it and generate from that point forward, doesn't appear to save any of the changes, add random generations to the undo history and/or starts to generate in the middle of the story, sometimes even deleting the prompt.

Models tested were "Erobus 6.7B (NSFW)" and "OPT Nerys 6B V2 (Hybrid)" on both Story and Adventure game modes.

**Comment by ebolam** [comment] 2022-11-03 23:21
@VladislavLiubasiuk That did it for me. Had to spam it as fast as I could, and it errored when I got all the way back to the beginning. That gives me something to work against. Hopefully that fixes any other similar behavior for the rest of the group.

**Comment by ebolam** [comment] 2022-11-03 23:57
OK. I think this is fixed now. Let me know if you get any more errors.

The problem was undo actions were not properly killing actions that had world info matches in them, leaving the text in the UI.

**Closed as completed by ebolam** 2022-11-03 23:57 UTC
Labels: bug
