### ISSUE TITLE
Still having problems editing inputs with WI entries

### ISSUE THREAD

**Issue by RaphaelNunes10** [ebolam/KoboldAI#289] opened 2022-11-05 23:48 UTC
Can't quite edit previous inputs containing World Info entries, some times receiving errors like this as a result:

> File "aiserver.py", line 537, in g
>     return f(*a, **k)
>            │  │    └ {}
>            │  └ ({'id': 4, 'text': '\n\n> **_<my_input>_**\n'},)
>            └ <function UI_2_Set_Selected_Text at 0x00000265649B05E0>
> 
>   File "aiserver.py", line 8280, in UI_2_Set_Selected_Text
>     koboldai_vars.actions[int(data['id'])] = data['text']
>     │                         │              └ {'id': 4, 'text': '\n\n> **_<my_input>_**\n'}
>     └ <koboldai_settings.koboldai_vars object at 0x00000265648C73A0>
> 
> IndexError: list index out of range

The edits are lost upon clicking away from the gametext area, or after processing the input accordingly with the edits, then reverting to the old input.

The client also keeps losing connection quite frequently while it's generating, what made me reload the page and click the submit button while it's generating at some point (don't know for sure if doing that is what causes the issue).

I've been hitting undo and regenerate quite often as well, but not in quick succession.

Other related issues were observed, such as WI entry duplication and loading the story requiring a new prompt and making the text uneditable unless the page is refreshed.

Removing the input with the WI entry circumvents this issue.

Haven't tested multiple inputs with WI entries.

**Comment by ebolam** [comment] 2022-11-09 23:20
Your first error seems to be something around editing a text chunk that the backend doesn't see anymore, which I can only imagine as some kind of frontend and backend sync problem. Are you able to reproduce it? 

For the generate bug, does it die before token streaming (or if you have that off, when it starts giving % complete info) or after?

The WI entry has a issue on here, still trying to get it to trigger reliably, but I did make an update recently (within the last week) that fixed one of the issues I saw, so if you see it again let me know (or have a way to trigger it with the sample story)

I think the prompt issue is fixed now. That one I saw earlier in the week and got that cleared (might have been the weekend)

**Closed as completed** 2022-12-14 14:23 UTC
Labels: bug, Waiting to reproduce
